arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1_to_base
    - joint2_to_joint1
    - joint3_to_joint2
    - joint4_to_joint3
    - joint5_to_joint4
  gains:
    joint1_to_base:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2_to_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3_to_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4_to_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5_to_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_controller
  gains:
    gripper_controller:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
